///////////////////////////////////////////////////////////
//  BusquedaRecurso.cs
//  Implementation of the Class BusquedaRecurso
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:54
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class BusquedaRecurso {

	private Personal Creador;
	private string Observador;
	private Oficina Oficina;
	public Necesidad m_Necesidad;
	public Personal m_Personal;

	public BusquedaRecurso(){

	}

	~BusquedaRecurso(){

	}

}//end BusquedaRecurso