///////////////////////////////////////////////////////////
//  CargoEmpleado.cs
//  Implementation of the Class CargoEmpleado
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:54
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CargoEmpleado : ClaseGenerica {

	private Permiso Permisos;

	public CargoEmpleado(){

	}

	~CargoEmpleado(){

	}

	public Permiso Permisos{
		get{
			return Permisos;
		}
		set{
			Permisos = value;
		}
	}

}//end CargoEmpleado