///////////////////////////////////////////////////////////
//  ClaseGenerica.cs
//  Implementation of the Class ClaseGenerica
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:54
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class ClaseGenerica {

	private char Descripcion;
	private int ID;

	public ClaseGenerica(){

	}

	~ClaseGenerica(){

	}

	public char Descripcion{
		get{
			return Descripcion;
		}
		set{
			Descripcion = value;
		}
	}

	public int ID{
		get{
			return ID;
		}
		set{
			ID = value;
		}
	}

}//end ClaseGenerica