///////////////////////////////////////////////////////////
//  Empresa.cs
//  Implementation of the Class Empresa
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Empresa {

	public Oficina m_Oficina;

	public Empresa(){

	}

	~Empresa(){

	}

}//end Empresa