///////////////////////////////////////////////////////////
//  EstadoPostulante.cs
//  Implementation of the Class EstadoPostulante
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class EstadoPostulante : ClaseGenerica {

	public Postulante m_Postulante;

	public EstadoPostulante(){

	}

	~EstadoPostulante(){

	}

}//end EstadoPostulante