///////////////////////////////////////////////////////////
//  Genero.cs
//  Implementation of the Class Genero
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Genero : ClaseGenerica {

	public Persona m_Persona;

	public Genero(){

	}

	~Genero(){

	}

}//end Genero