///////////////////////////////////////////////////////////
//  Gerente.cs
//  Implementation of the Class Gerente
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Gerente : Personal {

	public RRHH m_RRHH;
	public Necesidad m_Necesidad;

	public Gerente(){

	}

	~Gerente(){

	}

}//end Gerente