///////////////////////////////////////////////////////////
//  Localidad.cs
//  Implementation of the Class Localidad
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Localidad : ClaseGenerica {

	private Barrio Barrio;
	public Barrio m_Barrio;
	public Direccion m_Direccion;

	public Localidad(){

	}

	~Localidad(){

	}

	public Barrio Barrio{
		get{
			return Barrio;
		}
		set{
			Barrio = value;
		}
	}

}//end Localidad