///////////////////////////////////////////////////////////
//  Organigrama personal.cs
//  Implementation of the Class Organigrama personal
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Organigrama personal {

	private Personal Subordinados;
	private Personal Superior;
	public Personal m_Personal;

	public Organigrama personal(){

	}

	~Organigrama personal(){

	}

}//end Organigrama personal