///////////////////////////////////////////////////////////
//  Permiso.cs
//  Implementation of the Class Permiso
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Permiso : ClaseGenerica {

	public CargoEmpleado m_CargoEmpleado;

	public Permiso(){

	}

	~Permiso(){

	}

}//end Permiso