///////////////////////////////////////////////////////////
//  Personal.cs
//  Implementation of the Class Personal
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Personal : Persona {

	private CargoEmpleado Cargo;
	private Direccion Direccion;
	private Fecha FechaIngreso;
	private Fecha FechaNacimiento;
	private int Legajo;
	private Oficina Oficina;
	private Telefono Telefono;
	public CargoEmpleado m_CargoEmpleado;
	public Oficina m_Oficina;
	public Necesidad m_Necesidad;
	public BusquedaRecurso m_BusquedaRecurso;
	public Postulante m_Postulante;

	public Personal(){

	}

	~Personal(){

	}

	public CargoEmpleado Cargo{
		get{
			return Cargo;
		}
		set{
			Cargo = value;
		}
	}

	public Direccion Direccion{
		get{
			return Direccion;
		}
		set{
			Direccion = value;
		}
	}

	public Fecha FechaIngreso{
		get{
			return FechaIngreso;
		}
		set{
			FechaIngreso = value;
		}
	}

	public Fecha FechaNacimiento{
		get{
			return FechaNacimiento;
		}
		set{
			FechaNacimiento = value;
		}
	}

	public int Legajo{
		get{
			return Legajo;
		}
		set{
			Legajo = value;
		}
	}

	public Oficina Oficina{
		get{
			return Oficina;
		}
		set{
			Oficina = value;
		}
	}

	public Telefono Telefono{
		get{
			return Telefono;
		}
		set{
			Telefono = value;
		}
	}

}//end Personal