///////////////////////////////////////////////////////////
//  Persona.cs
//  Implementation of the Class Persona
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:39:21
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Persona {

	private char Apellido;
	private char Email;
	private Genero Genero;
	private int ID;
	private char Nombre;

	public Persona(){

	}

	~Persona(){

	}

	public char getApellido(){

		return 0;
	}

	public char getEmail(){

		return 0;
	}

	public Genero getGenero(){

		return null;
	}

	public int getID(){

		return 0;
	}

	public char getNombre(){

		return 0;
	}

	/// 
	/// <param name="newVal"></param>
	public void setApellido(char newVal){

	}

	/// 
	/// <param name="newVal"></param>
	public void setEmail(char newVal){

	}

	/// 
	/// <param name="newVal"></param>
	public void setGenero(Genero newVal){

	}

	/// 
	/// <param name="newVal"></param>
	public void setID(int newVal){

	}

	/// 
	/// <param name="newVal"></param>
	public void setNombre(char newVal){

	}

}//end Persona