///////////////////////////////////////////////////////////
//  Postulante.cs
//  Implementation of the Class Postulante
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Postulante : Persona {

	private string URL_CV;
	public BusquedaRecurso m_BusquedaRecurso;

	public Postulante(){

	}

	~Postulante(){

	}

}//end Postulante