///////////////////////////////////////////////////////////
//  Prioridad.cs
//  Implementation of the Class Prioridad
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Prioridad : ClaseGenerica {

	public Necesidad m_Necesidad;

	public Prioridad(){

	}

	~Prioridad(){

	}

}//end Prioridad