///////////////////////////////////////////////////////////
//  RRHH.cs
//  Implementation of the Class RRHH
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class RRHH : Personal {

	public Empleado m_Empleado;
	public BusquedaRecurso m_BusquedaRecurso;

	public RRHH(){

	}

	~RRHH(){

	}

}//end RRHH