///////////////////////////////////////////////////////////
//  Telefono.cs
//  Implementation of the Class Telefono
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Telefono {

	private char Empresa;
	private int Numero;
	private TipoTelefono TipoTelefono;
	public Personal m_Personal;
	public TipoTelefono m_TipoTelefono;

	public Telefono(){

	}

	~Telefono(){

	}

	public char Empresa{
		get{
			return Empresa;
		}
		set{
			Empresa = value;
		}
	}

	public int Numero{
		get{
			return Numero;
		}
		set{
			Numero = value;
		}
	}

	public TipoTelefono TipoTelefono{
		get{
			return TipoTelefono;
		}
		set{
			TipoTelefono = value;
		}
	}

}//end Telefono