///////////////////////////////////////////////////////////
//  Barrio.cs
//  Implementation of the Class Barrio
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:54
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data;



public class Barrio : ClaseGenerica
{
    public DataTable VerBarriosEnLocalidad(int claveLocalidad)
    {
        DALBarrio barrios = new DALBarrio();
        return barrios.sp_VerBarriosEnLocalidad(claveLocalidad);
    }
}//end Barrio