///////////////////////////////////////////////////////////
//  Barrio.cs
//  Implementation of the Class Barrio
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:54
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Barrio : ClaseGenerica 
{

}//end Barrio