///////////////////////////////////////////////////////////
//  CargoEmpleado.cs
//  Implementation of the Class CargoEmpleado
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:54
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data;



public class CargoEmpleado : ClaseGenerica {

	private List<Permiso> _permisos = new List<Permiso>();

	public List<Permiso> Permisos
	{
		get
		{
			return _permisos;
		}
		set
		{
			_permisos = value;
		}
	}
	public DataTable vercargos()
	{
		DALCargo cargos = new DALCargo();
		return cargos.sp_VerTodoCargo();
	}

}//end CargoEmpleado