///////////////////////////////////////////////////////////
//  ClaseGenerica.cs
//  Implementation of the Class ClaseGenerica
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:54
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class ClaseGenerica {

	private char _descripcion;
	private int _id;


	public char Descripcion
	{
		get
		{
			return _descripcion;
		}
		set
		{
			_descripcion = value;
		}
	}

	public int ID
	{
		get
		{
			return _id;
		}
		set
		{
			_id = value;
		}
	}

}//end ClaseGenerica