///////////////////////////////////////////////////////////
//  Direccion.cs
//  Implementation of the Class Direccion
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:54
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Direccion {

	private Barrio _barrio;
	private char _calle;
	private Localidad _localidad;
	private int _numero;
	private Provincia _provincia;
	private TipoDireccion _tipoDireccion;

	public Barrio Barrio
	{
		get
		{
			return _barrio;
		}
		set
		{
			_barrio = value;
		}
	}

	public Localidad Localidad
	{
		get
		{
			return _localidad;
		}
		set
		{
			_localidad = value;
		}
	}

	public Provincia Provincia
	{
		get
		{
			return _provincia;
		}
		set
		{
			_provincia = value;
		}
	}

	public char Calle
	{
		get
		{
			return _calle;
		}
		set
		{
			_calle = value;
		}
	}

	public int Numero
	{
		get
		{
			return _numero;
		}
		set
		{
			_numero = value;
		}
	}

	public TipoDireccion TipoDireccion
	{
		get
		{
			return _tipoDireccion;
		}
		set
		{
			_tipoDireccion = value;
		}

	}

}//end Direccion