///////////////////////////////////////////////////////////
//  Fecha.cs
//  Implementation of the Class Fecha
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Fecha 
{

	private int _año;
	private int _dia;
	private int _mes;

	public int Año
	{
		get
		{
			return _año;
		}
		set
		{
			_año = value;
		}
	}

	public int Dia
	{
		get
		{
			return _dia;
		}
		set
		{
			_dia = value;
		}
	}

	public int Mes
	{
		get
		{
			return _mes;
		}
		set
		{
			_mes = value;
		}
	}

}//end Fecha