///////////////////////////////////////////////////////////
//  Necesidad.cs
//  Implementation of the Class Necesidad
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data;
using System.Data.SqlClient;



public class Necesidad : ClaseGenerica {

	private Personal _creador;
	private Fecha _fechaCierre;
	private Fecha _fechaCreacion;
	private string _observacion;
	private Prioridad _prioridad;

	public Personal Creador
	{
		get
		{
			return _creador;
		}
		set
		{
			_creador = value;
		}
	}

	public Fecha FechaCierre
	{
		get
		{
			return _fechaCierre;
		}
		set
		{
			_fechaCierre = value;
		}
	}

	public Fecha FechaCreacion
	{
		get
		{
			return _fechaCreacion;
		}
		set
		{
			_fechaCreacion = value;
		}
	}

	public string Observacion
	{
		get
		{
			return _observacion;
		}
		set
		{
			_observacion = value;
		}
	}

	public Prioridad Prioridad
	{
		get
		{
			return _prioridad;
		}
		set
		{
			_prioridad = value;
		}
	}

	public DataTable VerTodoNecesidad()
	{
		return new VerTodoNecesidad().sp_VerTodoNecesidad();
	}

	public void CrearNecesidad(string Asunto, string Necesidad, int Creador)
	{
		new CrearNecesidad().sp_CrearNecesidad(Asunto, Necesidad, Creador);
	}
	public DataTable VerNecesidadPorID(int ID)
	{
		return new VerNecesidadPorID().sp_VerNecesidadPorID(ID);
	}

	public DataTable VerPropuestosDeNecesidad(int necesidad)
	{
		return new VerPropuestos().sp_VerPropuestosDeNecesidad(necesidad);
	}

}//end Necesidad