///////////////////////////////////////////////////////////
//  Oficina.cs
//  Implementation of the Class Oficina
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data;



public class Oficina : ClaseGenerica {

	private Direccion _direccion = new Direccion();

	public Direccion Direccion
	{
		get
		{
			return _direccion;
		}
		set
		{
			_direccion = value;
		}
	}

	public DataTable VerOficinas()
	{
		DALOficina oficinas = new DALOficina();
		return oficinas.sp_VerTodoOficina();
	}


}//end Oficina