///////////////////////////////////////////////////////////
//  Oficina.cs
//  Implementation of the Class Oficina
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Oficina : ClaseGenerica {

	private Direccion _direccion;

	public Direccion Direccion
	{
		get
		{
			return _direccion;
		}
		set
		{
			_direccion = value;
		}
	}

}//end Oficina