///////////////////////////////////////////////////////////
//  Organigrama personal.cs
//  Implementation of the Class Organigrama personal
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data;

public class OrganigramaPersonal 
{
	private List<Personal> _subordinados;
	private Personal _superior;

	public List<Personal> Subordinados
	{
		get
		{
			return _subordinados;
		}
		set
		{
			_subordinados = value;
		}
	}

	public Personal Superior
	{
		get
		{
			return _superior;
		}
		set
		{
			_superior = value;
		}
	}

	public DataTable VerSupervisor(int ID)
	{
		return new VerOrganigramaPersonal().sp_VerSupervisor(ID);
	}

	public DataTable VerSupervisados(int ID)
	{
		return new VerOrganigramaPersonal().sp_VerSupervisados(ID);
	}

}//end Organigrama personal