///////////////////////////////////////////////////////////
//  Persona.cs
//  Implementation of the Class Persona
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:39:21
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public abstract class Persona {

	private string _apellido;
	private string _email;
	private Genero _genero;
	private int _id;
	private string _nombre;

	public string Apellido
	{
		get
		{
			return _apellido;
		}
		set
		{
			_apellido = value;
		}
	}

	public string Email
	{
		get
		{
			return _email;
		}
		set
		{
			_email = value;
		}
	}

	public Genero Genero
	{
		get
		{
			return _genero;
		}
		set
		{
			_genero = value;
		}
	}

	public int ID
	{
		get
		{
			return _id;
		}
		set
		{
			_id = value;
		}
	}

	public string Nombre
	{
		get
		{
			return _nombre;
		}
		set
		{
			_nombre = value;
		}
	}

	/// 
	/// <param name="newVal"></param>
	public void setApellido(char newVal){

	}

	/// 
	/// <param name="newVal"></param>
	public void setEmail(char newVal){

	}

	/// 
	/// <param name="newVal"></param>
	public void setGenero(Genero newVal){

	}

	/// 
	/// <param name="newVal"></param>
	public void setID(int newVal){

	}

	/// 
	/// <param name="newVal"></param>
	public void setNombre(char newVal){

	}

}//end Persona