///////////////////////////////////////////////////////////
//  Personal.cs
//  Implementation of the Class Personal
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data;
using System.Data.SqlClient;



public class Personal : Persona {

	private CargoEmpleado _cargo;
	private Direccion _direccion;
	private Fecha _fechaIngreso;
	private Fecha _fechaNacimiento;
	private int _legajo;
	private Oficina _oficina;
	private Telefono _telefono;
	private OrganigramaPersonal _organigrama;
	private string _contraseña;

	public CargoEmpleado Cargo
	{
		get
		{
			return _cargo;
		}
		set
		{
			_cargo = value;
		}
	}

	public Direccion Direccion
	{
		get
		{
			return _direccion;
		}
		set
		{
			_direccion = value;
		}
	}

	public Fecha FechaIngreso
	{
		get
		{
			return _fechaIngreso;
		}
		set
		{
			_fechaIngreso = value;
		}
	}

	public Fecha FechaNacimiento
	{
		get
		{
			return _fechaNacimiento;
		}
		set
		{
			_fechaNacimiento = value;
		}
	}

	public int Legajo
	{
		get
		{
			return _legajo;
		}
		set
		{
			_legajo = value;
		}
	}

	public Oficina Oficina
	{
		get
		{
			return _oficina;
		}
		set
		{
			_oficina = value;
		}
	}

	public Telefono Telefono
	{
		get
		{
			return _telefono;
		}
		set
		{
			_telefono = value;
		}
	}

	public OrganigramaPersonal Organigrama
	{
		get
		{
			return _organigrama;
		}
		set
		{
			_organigrama = value;
		}
	}

	public string Contraseña
	{
		get
		{
			return _contraseña;
		}
		set
		{
			_contraseña = value;
		}
	}

	public DataTable ComprobarUsuario(string legajo, string contraseña)
	{
		return (new personalLogin()).ComprobarUsuario(legajo, contraseña);
	}

}//end Personal