///////////////////////////////////////////////////////////
//  Telefono.cs
//  Implementation of the Class Telefono
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:55
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Telefono {

	private string _empresa;
	private int _numero;
	private TipoTelefono _tipoTelefono;

	public string Empresa
	{
		get
		{
			return _empresa;
		}
		set
		{
			_empresa = value;
		}
	}

	public int Numero
	{
		get
		{
			return _numero;
		}
		set
		{
			_numero = value;
		}
	}

	public TipoTelefono TipoTelefono
	{
		get
		{
			return _tipoTelefono;
		}
		set
		{
			_tipoTelefono = value;
		}
	}

}//end Telefono