///////////////////////////////////////////////////////////
//  TipoDireccion.cs
//  Implementation of the Class TipoDireccion
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:56
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class TipoDireccion : ClaseGenerica 
{

}//end TipoDireccion