///////////////////////////////////////////////////////////
//  TipoTelefono.cs
//  Implementation of the Class TipoTelefono
//  Generated by Enterprise Architect
//  Created on:      22-may.-2020 17:37:56
//  Original author: Haskell
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data;
using System.Reflection;

public class TipoTelefono : ClaseGenerica 
{
    public DataTable VerTiposDeTelefono()
    {
        DALTipoTelefono telefonos = new DALTipoTelefono();
        return telefonos.sp_VerTodoTipoTelefono();
    }

}//end TipoTelefono